### This notebook is written by Jiawen Liang for the AccFin PhD workshop: Python for Data Analysis in Nov 2022. Please do not circulate without permission.

# Session 3: Data analysis

## NumPy
- NumPy basics
- Numerical computing

## Pandas
- Pandas basics
- Data analysis

Note: NumPy and Pandas is included in the Anaconda Python

# Numpy
- a package library for Python
- support large, multi-dimensional arrays and matrices
- mathematical functions

## Array
- array: a very important data structures
- one-dimensional array: a vector of real numbers. single row
- N-dimensional array (N>1): matrix of elements

In [1]:
# one-dimentsion array
v = [1,2,3,4,5,2.4,2.4,34.2]

In [2]:
# N-dimensional array
m = [v, v, v]
m

[[1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
 [1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
 [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]]

In [3]:
# select rows via simple indexing
m[2] #the third rows

[1, 2, 3, 4, 5, 2.4, 2.4, 34.2]

In [4]:
# select rows via double indexing
m[2][0] #third row, first number

1

In [5]:
# N-dimensional array can be combined together too.
c =[m,m]
c

[[[1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
  [1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
  [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]],
 [[1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
  [1, 2, 3, 4, 5, 2.4, 2.4, 34.2],
  [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]]]

In [6]:
# if we combine arrays in this way, the combined object will change when the original objects change.
v = [1,2,3,4,5,2.4,2.4,34.2]
m = [v, v]
m

[[1, 2, 3, 4, 5, 2.4, 2.4, 34.2], [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]]

In [7]:
v[0] = "A"
m

[['A', 2, 3, 4, 5, 2.4, 2.4, 34.2], ['A', 2, 3, 4, 5, 2.4, 2.4, 34.2]]

In [8]:
# This can be avoided by using the deepcopy() function of the copy module
from copy import deepcopy
v = [1,2,3,4,5,2.4,2.4,34.2]
m = 2 * [deepcopy(v)]
m

[[1, 2, 3, 4, 5, 2.4, 2.4, 34.2], [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]]

In [9]:
v[0] = "A"
m

[[1, 2, 3, 4, 5, 2.4, 2.4, 34.2], [1, 2, 3, 4, 5, 2.4, 2.4, 34.2]]

In [10]:
# you can create array with the lsit objects, but it is not really convenient.
# NumPy: numpy.ndarray is just such a class, built with the specific goal of handling n-dimensional arrays both conveniently and efficiently.
import numpy as np

In [11]:
a = np.array([1,2,3,4,5,2.4,2.4,34.2])
a

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  2.4,  2.4, 34.2])

In [12]:
type(a)

numpy.ndarray

In [13]:
a = np.array(['a','b','c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
type(a)

numpy.ndarray

In [15]:
# Create 3X2 double precision array initialized to all zeroes
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
# Create array initialized by list of lists
a = np.array([[0,1,2],['a','b','c']])
a

array([['0', '1', '2'],
       ['a', 'b', 'c']], dtype='<U21')

In [17]:
# a = np.array([0,1,2],['a','b','c']) # lack a square brackets

In [18]:
# create array using "arrange" function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [20]:
a = np.arange(10,20,3)
a

array([10, 13, 16, 19])

In [21]:
# select object by index
a = np.arange(10)
a[2:6]

array([2, 3, 4, 5])

In [22]:
a[:2]

array([0, 1])

In [23]:
# get value from N-dimensinal array
m = np.array([[0,1,2],[3,4,5]])
print(m)


[[0 1 2]
 [3 4 5]]


In [24]:
m[0,0]

0

In [25]:
m[0,:]

array([0, 1, 2])

In [26]:
m[:,-1]

array([2, 5])

In [27]:
m[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [28]:
# Modifying N-dimensional arrays
m[0,:] = 8
m

array([[8, 8, 8],
       [3, 4, 5]])

In [29]:
# Assign 1D array to all rows of 2D array
m[:,:] = np.array([3,6,9])
m

array([[3, 6, 9],
       [3, 6, 9]])

In [30]:
# reshape from 2X3 to 3X2
m.reshape(3,2)

array([[3, 6],
       [9, 3],
       [6, 9]])

In [31]:
# NumPy basic calculations
# Create 1D array
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
# Add 1D arrays elementwise a+a
a.sum()

28

In [33]:
# Compute dot product: a * a vector multipulation
np.dot(a, a)   # same as: (a * a).sum()

140

In [34]:
# Compute cross product
np.dot(a.reshape(4,2), a.reshape(2,4))

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47],
       [28, 41, 54, 67]])

In [35]:
a.std()

2.29128784747792

In [36]:
# Return the cumulative sum of the elements along a given axis.
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [37]:
# operation differences between array and list
a_list = [1,2,3,4,5]
print(a_list*2) # 2 a_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [38]:
a_array = np.array([1,2,3,4,5])
a_array

array([1, 2, 3, 4, 5])

In [39]:
a_array * 2 # multiple 2

array([ 2,  4,  6,  8, 10])

In [40]:
a_array ** 2

array([ 1,  4,  9, 16, 25])

In [41]:
# n-dimensional array mutiple
b = np.array([a, a * 2])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  2,  4,  6,  8, 10, 12, 14]])

In [42]:
b[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
b[0,1]

1

In [44]:
b.sum()

84

In [45]:
b.sum(axis=0) # sum row values in the same columns

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [46]:
b.sum(axis=1) # sum all columns values in the same row

array([28, 56])

# NumPy attributes

In [47]:
b.size

16

In [48]:
 b.itemsize

8

In [49]:
b.ndim

2

In [50]:
b.shape # 2X8 matrix

(2, 8)

In [51]:
# reshaping in general just provides another view on the same data. 
c = np.arange(10)
c.shape

(10,)

In [52]:
c = c.reshape((5,2))
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
c = c.reshape((2,5))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
#  transpose creates a new (temporary) object.
c.T 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [55]:
c.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [56]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
# boolean ndarray object
c>5 

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [58]:
c <8

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

In [59]:
c == 3

array([[False, False, False,  True, False],
       [False, False, False, False, False]])

In [60]:
# numpy.ndarray.astype
# Copy of the array, cast to a specified type.
(c == 3).astype(int)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [61]:
(c > 2) & (c < 8) 

array([[False, False, False,  True,  True],
       [ True,  True,  True, False, False]])

# Exercise for Numpy:
1. create an array [2,4,6,8,10,12]
2. reshape this array to 2X3
3. select the value on first row & second column after reshaping
3. transpose

## Pandas

- pandas is a library for data analysis 
- focus on tabular data (dataframe)
- pandas has many functions and data structures which are similar to **R**. Particularly related to:
   - Data frames.
   - Indexing.


## Pandas basics

In [63]:
import pandas as pd

In [64]:
# several ways to create df
df1 = pd.DataFrame([1,2,3,4,5], columns=["numbers"], index = ['a','b','c','d','e'])
df1

numbers
a        1
b        2
c        3
d        4
e        5

In [65]:
df2 = pd.DataFrame({'numbers': [1, 2,3,4,5]}, index=['a','b','c','d','e'])
df2

numbers
a        1
b        2
c        3
d        4
e        5

In [66]:
df3 = pd.DataFrame({'numbers': [1, 2,3,4,5]}, index=['a','b','c','d','e'])
df3

numbers
a        1
b        2
c        3
d        4
e        5

In [67]:
df4 = pd.DataFrame({'Binary_variable': [0,1,1], 'age': [18,20,25]})
df4

Binary_variable  age
0                0   18
1                1   20
2                1   25

In [68]:
# reading data file

import os #This package allows us to change our working directory

# Set our working directory
path = '/Users/liangjiawen/PycharmProjects/Python workshop/data'
os.chdir(path)

filename = 'stock_prices.csv'
price_df = pd.read_csv(filename)

In [69]:
price_df

date        AAPL         GE      AMD        WMT        BAC  \
0     29/12/1989    0.117203   0.352438   3.9375   3.486070   1.752478   
1     02/01/1990    0.123853   0.364733   4.1250   3.660858   1.766686   
2     03/01/1990    0.124684   0.364050   4.0000   3.660858   1.780897   
3     04/01/1990    0.125100   0.362001   3.9375   3.641439   1.743005   
4     05/01/1990    0.125516   0.358586   3.8125   3.602595   1.705114   
...          ...         ...        ...      ...        ...        ...   
7121  05/04/2018  172.800003  13.430000  10.0200  87.809998  30.320000   
7122  06/04/2018  168.380005  13.060000   9.6100  86.690002  29.629999   
7123  09/04/2018  170.050003  12.830000   9.5300  86.279999  29.870001   
7124  10/04/2018  173.250000  13.050000   9.9800  86.449997  30.480000   
7125  11/04/2018  172.440002  12.970000   9.8200  85.910004  29.900000   

              T        XOM    RRC        BBY        PFE         JPM  
0      2.365775   1.766756    NaN   0.166287   0.110818    1.827968  
1      2.398184   1.766756    NaN   0.173216   0.113209    1.835617  
2      2.356516   1.749088    NaN   0.194001   0.113608    1.896803  
3      2.403821   1.731422    NaN   0.190537   0.115402    1.904452  
4      2.287973   1.722587    NaN   0.190537   0.114405    1.912100  
...         ...        ...    ...        ...        ...         ...  
7121  35.632843  76.019997  14.52  72.120003  35.730000  111.879997  
7122  35.130001  74.870003  13.97  70.489998  35.169998  109.089996  
7123  35.169998  74.870003  13.93  69.820000  35.459999  110.400002  
7124  35.810001  77.070000  14.78  71.720001  35.950001  112.510002  
7125  35.250000  77.430000  14.99  70.910004  35.790001  110.620003  

[7126 rows x 12 columns]

In [70]:
# you can read csv with the path from content root (under the same main fold of your coding file)
price2_df = pd.read_csv('data/stock_prices.csv')
price2_df

FileNotFoundError: [Errno 2] No such file or directory: 'data/stock_prices.csv'

# download data from a website

In [ ]:
asset_df.columns

In [ ]:
# save this df
asset_df.to_csv("data/spy_vix_data.csv")

## typical operations on a DataFrame object

In [ ]:
# check how large of your df
price_df.shape

In [ ]:
# grabs the first five rows
price_df.head()

In [ ]:
# use the default index
price_df.reset_index(inplace=True)

In [ ]:
price_df.columns

In [ ]:
price_df.index

## index, select and assign
- iloc[ , ], select values on the rows/ columns or value with row and column index by their positions.

- loc[ , ], Label-based selection. selec by values instead of positions.

In [ ]:
price_df["AAPL"][0]

In [ ]:
# To select the first row of data in a DataFrame
price_df.iloc[0]

In [ ]:
# To select all the rows on first column of data in a DataFrame=
price_df.iloc[:,0]

In [ ]:
price_df.iloc[:5,0]

In [ ]:
price_df.iloc[1:3,0]

In [ ]:
price_df.iloc[[1,2],0]

In [ ]:
price_df.iloc[[-5],0]

In [ ]:
# label based
price_df.loc[0,"AAPL"]

In [ ]:
price_df.loc[0,["AAPL", "GE", "AMD"]]

In [ ]:
# Manipulating the index
# re-set index
price_df.set_index('date', inplace=True)
price_df

In [ ]:
# codintional selection
price_df.AAPL > 5

In [ ]:
price_df.index == "29/12/1989"

In [ ]:
price_df.loc[price_df.AAPL > 5]

In [ ]:
# select the rows without Nan values
price_df.loc[price_df.AAPL.notnull()]

In [ ]:
# assign data
price_df["GE"] = 10
price_df["GE"]

In [ ]:
# append a row
new_row = price_df.iloc[0]
new_row

In [ ]:
price_df.append(new_row)

In [ ]:
# append a column
new_column = price_df["AAPL"]
price_df["new_column"] = new_column
price_df

In [ ]:
# drop a column / row
price_df.drop("new_column", axis=1, inplace=True)


In [ ]:
price_df

In [ ]:
price_df.drop("29/12/1989", axis=0, inplace=True)
price_df

# Summary statitics

In [ ]:
# basic information about this dataset
price_df.info()

In [ ]:
# summary statistics
price_df.describe()

In [ ]:
# keep 3 decimal places
price_df.describe().round(3)

In [ ]:
price_df["AAPL"].describe()

In [ ]:
price_df["AAPL"].mean()

In [ ]:
price_df["AAPL"].std()

In [ ]:
price_df["AAPL"].median()

In [ ]:
# To see a list of unique values we can use the unique() function
price_df["AAPL"].unique()

In [ ]:
len(price_df["AAPL"].unique())

In [ ]:
# to check if all values in this column are unique
len(price_df["AAPL"].unique()) == len(price_df["AAPL"])

In [ ]:
# to see a list of unique values and how often they occur in this column
price_df["AAPL"].value_counts()

In [ ]:
# to see the asset returns
return_df = price_df.pct_change()
return_df

In [ ]:
# You can also use NumPy for df objects
np.mean(price_df)

In [ ]:
np.log(price_df)

In [ ]:
np.sqrt(abs(price_df))

In [ ]:
np.sqrt(abs(price_df)).sum()

In [ ]:
# basic visualization
import matplotlib.pyplot as plt
price_df.plot()
plt.show()

In [ ]:
return_df.plot()
plt.show()

# Exercise for Pandas:

1. Use this dataset called "spy_prices.csv" in the data folder. Then, import it as a Pandas dataframe called "stocks_df" and take the mean, median and standard deviation of the spy prices.

2. Print each on a new line with the word: 'Mean', 'Median' and 'Std. Dev.' right about each.